using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StarWarsProject1.Models
{
    public class FavQuote
    {
        [Required] //this will be autogenerated
        [Display(Name ="Quote ID")]
        public int QuoteID { get; set; }

        [Required] //this will be a dynamic dropdown of the list of movies the user entered in SeenMovies
        [Display(Name = "Movie Title")]
        public string MovieTitle { get; set; }

        [Required] //this will be the quote the user enters
        [StringLength(150,ErrorMessage ="Must be under 150 characters long.")]
        [Display(Name = "Favorite Quote")]
        public string Quote { get; set; }

        [Required] //this will be the character name of whoever said the quote, entered by the user
        [StringLength(20, ErrorMessage ="Must be under 20 characters long.")]
        [Display(Name ="Who Said It")]
        public string CharacterName { get; set; }
    }
}