using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StarWarsProject1.Models
{
    public class MovieReview
    {
        [Required] //this will be autogenerated
        [Display(Name ="Review ID")]
        public int ReviewID { get; set; }

        [Required] //this will be a dynamic dropdown of the movies they entered in SeenMovies
        [Display(Name ="Movie Title")]
        public string MovieTitle { get; set; }

        [Required] //this will be the user's review of the movie (possibly also a hardcoded dropdown of Great, Good, Bad, Awful)
        [Display(Name = "Movie Review")]
        public string Review { get; set; }
    }
}