using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StarWarsProject1.Models
{
    public class SeenMovies
    {
        [Required] //the movie id will be autogenerated
        [Display(Name ="Movie ID")]
        public int MovieID { get; set; }

        [Required] //the user will type in the movie title
        [StringLength(50, ErrorMessage = "Must be under 50 characters long")]
        [Display(Name ="Movie Title")]
        public string MovieTitle { get; set; }

        [Required] //the movie type will be a hard coded dropdown list
        [StringLength(10)]
        [Display(Name = "Movie Type")]
        public string MovieType { get; set; }
    }
}